# Generated by Django 4.2.2 on 2024-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0003_sensordata_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='pub_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
